a,b= input("Please enter number a and b \n").split()
print(f" a+b= {int(a)+int(b)}")
print(f" a-b= {int(a)-int(b)}")
print(f" a*b= {int(a)*int(b)}")
print(f" a/b= {int(a)/int(b)}")
print(f" a%b= {int(a)%int(b)}")
