# -*- coding: utf-8 -*-
"""assgn7_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AzHptnGwZ_tcm6PXRxRYnSXT7SacYqZC
"""

import sympy as sym
x=sym.Symbol('x')
x=sym.diff(x**2+3*x+2)
print(x)

x1=0
learning_rate=.01
step_size=1
df=lambda x:2*x+3
precision=0.00000001
iter=0
while step_size > precision:
    initial_x1=x1

    x1=x1-learning_rate*df(x1)

    step_size=abs(initial_x1-x1)
    
print(x1)