# -*- coding: utf-8 -*-
"""assgn7_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/102oj546d-nAc0CYT8a-xZhJ4AvpoUS5w
"""

learning_rate=.01
init_x1=2
init_x2=2
step_size1=1
step_size2=1
df1=lambda x1:2*x1
df2=lambda x2:2*x2
precision=0.00000001
iter=0
while step_size1 > precision and step_size2 > precision:
    init_x11=init_x1
    init_x22 =init_x2
    init_x1=init_x1-learning_rate*df1(init_x1)
    step_size1=abs(init_x11-init_x1)
    init_x2 = init_x2 - learning_rate * df2(init_x2)
    step_size2 = abs(init_x22 - init_x2)
    

print(init_x1,init_x2)